### ISSUE TITLE
Stops Table

### ISSUE THREAD

**Issue by jonlukewtafe** [AllenWorker/Heritage-Walks#7]
The stops table appears to be unable to fit on screen properly if the description of the stop is too long. I assume that the same issue will be encountered when dealing with trails with long descriptions as well. The text will need to wrap down.

**Comment by jonlukewtafe** [comment]
Turns out this hasn't completely been fixed as of 10/06/2019. This is a minor issue and is not of a high priority at the moment.

**Comment by jonlukewtafe** [comment]
Issue has almost been fixed, however, it still occurs if the description doesn't have any line breaks.

**Comment by TreliaGT** [comment]
Believe that this issue is fixed in master
